#!/bin/bash

check_distro()
{

	IS_PRERELEASE=$(lsb_release -d | grep 'Ubuntu .*development' >& /dev/null; echo $?)
	if [[ $IS_PRERELEASE -eq 0 ]]; then
		print_status "Your distribution, identified as \"$(lsb_release -d -s)\", is a pre-release version of Ubuntu"
		exit 1
	fi

	DISTRO=$(lsb_release -c -s)

	check_alt() {
		if [ "X${DISTRO}" == "X${2}" ]; then
			DISTRO="${4}"
		fi
	}

	check_alt "Astra Linux"    "orel"            "Debian"        "stretch"
	check_alt "BOSS"           "anokha"          "Debian"        "wheezy"
	check_alt "BOSS"           "anoop"           "Debian"        "jessie"
	check_alt "BOSS"           "drishti"         "Debian"        "stretch"
	check_alt "BOSS"           "unnati"          "Debian"        "buster"
	check_alt "BOSS"           "urja"            "Debian"        "bullseye"
	check_alt "bunsenlabs"     "bunsen-hydrogen" "Debian"        "jessie"
	check_alt "bunsenlabs"     "helium"          "Debian"        "stretch"
	check_alt "bunsenlabs"     "lithium"         "Debian"        "buster"
	check_alt "Devuan"         "jessie"          "Debian"        "jessie"
	check_alt "Devuan"         "ascii"           "Debian"        "stretch"
	check_alt "Devuan"         "beowulf"         "Debian"        "buster"
	check_alt "Devuan"         "chimaera"        "Debian"        "bullseye"
	check_alt "Devuan"         "ceres"           "Debian"        "sid"
	check_alt "Devuan"         "daedalus"        "Debian"        "bookworm"
	check_alt "Deepin"         "panda"           "Debian"        "sid"
	check_alt "Deepin"         "unstable"        "Debian"        "sid"
	check_alt "Deepin"         "stable"          "Debian"        "buster"
	check_alt "Deepin"         "apricot"         "Debian"        "buster"
	check_alt "Deepin"         "beige"           "Debian"        "bookworm"
	check_alt "elementaryOS"   "luna"            "Ubuntu"        "precise"
	check_alt "elementaryOS"   "freya"           "Ubuntu"        "trusty"
	check_alt "elementaryOS"   "loki"            "Ubuntu"        "xenial"
	check_alt "elementaryOS"   "juno"            "Ubuntu"        "bionic"
	check_alt "elementaryOS"   "hera"            "Ubuntu"        "bionic"
	check_alt "elementaryOS"   "odin"            "Ubuntu"        "focal"
	check_alt "elementaryOS"   "jolnir"          "Ubuntu"        "focal"
	check_alt "elementaryOS"   "horus"           "Ubuntu"        "jammy"
	check_alt "Kali"           "sana"            "Debian"        "jessie"
	check_alt "Kali"           "kali-rolling"    "Debian"        "bullseye"
	check_alt "Linux Mint"     "maya"            "Ubuntu"        "precise"
	check_alt "Linux Mint"     "qiana"           "Ubuntu"        "trusty"
	check_alt "Linux Mint"     "rafaela"         "Ubuntu"        "trusty"
	check_alt "Linux Mint"     "rebecca"         "Ubuntu"        "trusty"
	check_alt "Linux Mint"     "rosa"            "Ubuntu"        "trusty"
	check_alt "Linux Mint"     "sarah"           "Ubuntu"        "xenial"
	check_alt "Linux Mint"     "serena"          "Ubuntu"        "xenial"
	check_alt "Linux Mint"     "sonya"           "Ubuntu"        "xenial"
	check_alt "Linux Mint"     "sylvia"          "Ubuntu"        "xenial"
	check_alt "Linux Mint"     "tara"            "Ubuntu"        "bionic"
	check_alt "Linux Mint"     "tessa"           "Ubuntu"        "bionic"
	check_alt "Linux Mint"     "tina"            "Ubuntu"        "bionic"
	check_alt "Linux Mint"     "tricia"          "Ubuntu"        "bionic"
	check_alt "Linux Mint"     "ulyana"          "Ubuntu"        "focal"
	check_alt "Linux Mint"     "ulyssa"          "Ubuntu"        "focal"
	check_alt "Linux Mint"     "uma"             "Ubuntu"        "focal"
	check_alt "Linux Mint"     "una"             "Ubuntu"        "focal"
	check_alt "Linux Mint"     "vanessa"         "Ubuntu"        "jammy"
	check_alt "Linux Mint"     "vera"            "Ubuntu"        "jammy"
	check_alt "Liquid Lemur"   "lemur-3"         "Debian"        "stretch"
	check_alt "LMDE"           "betsy"           "Debian"        "jessie"
	check_alt "LMDE"           "cindy"           "Debian"        "stretch"
	check_alt "LMDE"           "debbie"          "Debian"        "buster"
	check_alt "LMDE"           "elsie"           "Debian"        "bullseye"
	check_alt "MX Linux 17"    "Horizon"         "Debian"        "stretch"
	check_alt "MX Linux 18"    "Continuum"       "Debian"        "stretch"
	check_alt "MX Linux 19"    "patito feo"      "Debian"        "buster"
	check_alt "MX Linux 21"    "wildflower"      "Debian"        "bullseye"
	check_alt "Pardus"         "onyedi"          "Debian"        "stretch"
	check_alt "Parrot"         "ara"             "Debian"        "bullseye"
	check_alt "PureOS"         "green"           "Debian"        "sid"
	check_alt "PureOS"         "amber"           "Debian"        "buster"
	check_alt "PureOS"         "byzantium"       "Debian"        "bullseye"
	check_alt "SolydXK"        "solydxk-9"       "Debian"        "stretch"
	check_alt "Sparky Linux"   "Tyche"           "Debian"        "stretch"
	check_alt "Sparky Linux"   "Nibiru"          "Debian"        "buster"
	check_alt "Sparky Linux"   "Po-Tolo"         "Debian"        "bullseye"
	check_alt "Tanglu"         "chromodoris"     "Debian"        "jessie"
	check_alt "Trisquel"       "toutatis"        "Ubuntu"        "precise"
	check_alt "Trisquel"       "belenos"         "Ubuntu"        "trusty"
	check_alt "Trisquel"       "flidas"          "Ubuntu"        "xenial"
	check_alt "Trisquel"       "etiona"          "Ubuntu"        "bionic"
	check_alt "Ubilinux"       "dolcetto"        "Debian"        "stretch"
	check_alt "Uruk GNU/Linux" "lugalbanda"      "Ubuntu"        "xenial"

	if [ "X${DISTRO}" == "Xdebian" ]; then
		print_status "Unknown Debian-based distribution, checking /etc/debian_version..."
		NEWDISTRO=$([ -e /etc/debian_version ] && cut -d/ -f1 < /etc/debian_version)
		if [ "X${NEWDISTRO}" == "X" ]; then
			print_status "Could not determine distribution from /etc/debian_version..."
		else
			DISTRO=$NEWDISTRO
			print_status "Found \"${DISTRO}\" in /etc/debian_version..."
		fi
	fi
}


checkdependencies()
{
	if [ -n "$cheked" ]; then
		return
	fi

	check_distro

	it=""

	isdependencies()
	{
		if [ "$(isset "$1")" = "OFF" ]; then
			sudo apt install "$1" -y
			print_status "$1 $D_DEPENSINST"
			it=1
		fi
	}
	isdependencies "lsb-release" 
	isdependencies "ca-certificates"
	isdependencies "apt-transport-https"
	isdependencies "gnupg"
	isdependencies "whiptail"
	isdependencies "p7zip-full"
	isdependencies "mc-data"
	isdependencies "xterm"
	isdependencies "curl"
	isdependencies "wget"

	if ! systemctl 2>/dev/null | grep -q loaded; then
		isdependencies "systemctl"
	fi

	if [ ! -f "/usr/local/bin/mkcert" ] && [ "$(isset 'mkcert')" = "OFF" ]; then
		isdependencies "libnss3-tools"
		sudo curl -JLO# "https://dl.filippo.io/mkcert/latest?for=linux/amd64" &>/dev/null
		sudo chmod +x mkcert-v*-linux-amd64
		sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
		print_status "mkcert $D_DEPENSINST"
		it=1 && sleep 1
	fi	

	clear
	#autologin
	if [ -n "$it" ] ; then
		echo "$D_DEPENSOK"
		sleep 3
		export cheked=1
		export urun="$USER"
		sudo -s -E bash "${0}"
		exit
	fi
}
